### ISSUE TITLE
Milestone 2 feedback: 

### ISSUE THREAD

**Issue by Abu-Hijleh** [data301-2020-winter2/course-project-group_1045#1]
Gotta say, I deeply enjoyed Mitch's markdown. 

Must fix: 

- [x] load data from the data folder instead of the gist URL 
- [x] Use relative addressing instead of absolute addressing (example: do not use "C:/Users/nolan/Data 301 Github/course-project-group_1045/analysis/scripts'")
- [x] add graph titles/ axis units (example, what unit is the charges in?)
